title: "Did AI Solve?"
description: "A website tracking whether AI has solved major open problems in math, science, and beyond."
baseurl: "/didaisolve"
url: "https://osolmaz.github.io"

# Add these new settings
permalink: "pretty"
markdown: kramdown

collections:
  problems:
    output: true
    permalink: /problems/:path/

# Where Jekyll should look for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Optional: Exclude files or directories from processing
exclude:
  - Gemfile
  - Gemfile.lock
